/*
 * This program as made by Misha Donais
 * On November 5th 2018
 * To perform various basic calculations
 */
import java.text.DecimalFormat;
/**
 *
 * @author midon7419
 */
public class MagicMathMethodsForm extends javax.swing.JFrame {

    /**
     * Creates new form MagicMathMethodsForm
     */
    public MagicMathMethodsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        maxlbl = new javax.swing.JLabel();
        maxtxt2 = new javax.swing.JTextField();
        maxtxt1 = new javax.swing.JTextField();
        maxbtn = new javax.swing.JButton();
        maxoutputlbl = new javax.swing.JLabel();
        maxlbl1 = new javax.swing.JLabel();
        mintxt2 = new javax.swing.JTextField();
        mintxt1 = new javax.swing.JTextField();
        minbtn = new javax.swing.JButton();
        minoutputlbl = new javax.swing.JLabel();
        powbtn = new javax.swing.JButton();
        powoutputlbl = new javax.swing.JLabel();
        powlbl = new javax.swing.JLabel();
        powtxt2 = new javax.swing.JTextField();
        powtxt1 = new javax.swing.JTextField();
        hypotbtn = new javax.swing.JButton();
        hypotoutputlbl = new javax.swing.JLabel();
        hypotlbl = new javax.swing.JLabel();
        hypottxt2 = new javax.swing.JTextField();
        hypottxt1 = new javax.swing.JTextField();
        floortxt = new javax.swing.JTextField();
        floorbtn = new javax.swing.JButton();
        flooroutputlbl = new javax.swing.JLabel();
        floorlbl = new javax.swing.JLabel();
        ceillbl = new javax.swing.JLabel();
        ceiltxt = new javax.swing.JTextField();
        ceilbtn = new javax.swing.JButton();
        ceiloutputlbl = new javax.swing.JLabel();
        sqrtlbl = new javax.swing.JLabel();
        sqrttxt = new javax.swing.JTextField();
        sqrtbtn = new javax.swing.JButton();
        sqrtoutputlbl = new javax.swing.JLabel();
        toRadianslbl = new javax.swing.JLabel();
        toRadianstxt = new javax.swing.JTextField();
        toRadiansbtn = new javax.swing.JButton();
        toRadiansoutputlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlelbl.setFont(new java.awt.Font("Saved By Zero", 0, 24)); // NOI18N
        titlelbl.setText("Magic Math Methods");

        maxlbl.setText("Enter two numbers and click the button. The program will display the largest of the two numbers:  ");

        maxtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxtxt2ActionPerformed(evt);
            }
        });

        maxtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxtxt1ActionPerformed(evt);
            }
        });

        maxbtn.setText("Calculate");
        maxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxbtnActionPerformed(evt);
            }
        });

        maxlbl1.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers:  ");

        mintxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mintxt2ActionPerformed(evt);
            }
        });

        mintxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mintxt1ActionPerformed(evt);
            }
        });

        minbtn.setText("Calculate");
        minbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minbtnActionPerformed(evt);
            }
        });

        powbtn.setText("Calculate");
        powbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powbtnActionPerformed(evt);
            }
        });

        powlbl.setText("Enter two numbers and click the button. The program will display the first number to the power of the second:");

        powtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powtxt2ActionPerformed(evt);
            }
        });

        powtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powtxt1ActionPerformed(evt);
            }
        });

        hypotbtn.setText("Calculate");
        hypotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotbtnActionPerformed(evt);
            }
        });

        hypotlbl.setText("Enter the length of two sides of a right angle triangle. The program will return the hypotenuse of the triangle:");

        hypottxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypottxt2ActionPerformed(evt);
            }
        });

        hypottxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypottxt1ActionPerformed(evt);
            }
        });

        floortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floortxtActionPerformed(evt);
            }
        });

        floorbtn.setText("Calculate");
        floorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorbtnActionPerformed(evt);
            }
        });

        floorlbl.setText("Enter a decimal value. The program will round the value down to the nearest integer:");

        ceillbl.setText("Enter a decimal value. The program will round the value up to the nearest integer:");

        ceiltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceiltxtActionPerformed(evt);
            }
        });

        ceilbtn.setText("Calculate");
        ceilbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceilbtnActionPerformed(evt);
            }
        });

        sqrtlbl.setText("Enter an integer. The program will display the square root of the integer:");

        sqrttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrttxtActionPerformed(evt);
            }
        });

        sqrtbtn.setText("Calculate");
        sqrtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtbtnActionPerformed(evt);
            }
        });

        toRadianslbl.setText("Enter an angle in degrees. The program will display the angle in radians:");

        toRadianstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRadianstxtActionPerformed(evt);
            }
        });

        toRadiansbtn.setText("Calculate");
        toRadiansbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRadiansbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(maxlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(maxtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(maxtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(maxbtn)
                                .addGap(34, 34, 34)
                                .addComponent(maxoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxlbl1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(mintxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(mintxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(minbtn)
                                        .addGap(34, 34, 34)
                                        .addComponent(minoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(titlelbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hypotlbl))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(ceiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(108, 108, 108)
                                    .addComponent(ceilbtn)
                                    .addGap(45, 45, 45)
                                    .addComponent(ceiloutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(floortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(110, 110, 110)
                                        .addComponent(floorbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(flooroutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(hypottxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(hypottxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(hypotbtn)
                                        .addGap(44, 44, 44)
                                        .addComponent(hypotoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(powlbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(powtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(powtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(powbtn)
                                        .addGap(44, 44, 44)
                                        .addComponent(powoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floorlbl)
                                    .addComponent(ceillbl)
                                    .addComponent(sqrtlbl)
                                    .addComponent(toRadianslbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sqrttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(108, 108, 108)
                                                .addComponent(sqrtbtn)
                                                .addGap(45, 45, 45)
                                                .addComponent(sqrtoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(toRadianstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(108, 108, 108)
                                                .addComponent(toRadiansbtn)
                                                .addGap(45, 45, 45)
                                                .addComponent(toRadiansoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelbl)
                .addGap(18, 18, 18)
                .addComponent(maxlbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxbtn)
                    .addComponent(maxoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxlbl1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mintxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mintxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minbtn)
                    .addComponent(minoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(powlbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(powoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(powtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(powtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(powbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hypotlbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hypotoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hypottxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hypottxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hypotbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(floorlbl)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flooroutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(floortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(floorbtn)))
                .addGap(18, 18, 18)
                .addComponent(ceillbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ceiloutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ceiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ceilbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sqrtlbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sqrtoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sqrttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sqrtbtn)))
                .addGap(18, 18, 18)
                .addComponent(toRadianslbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toRadiansoutputlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(toRadianstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toRadiansbtn)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maxtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxtxt2ActionPerformed

    private void maxtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxtxt1ActionPerformed

    private void maxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxbtnActionPerformed

        //Max calc code
        //Inputs
        double maxValue1;
        maxValue1 = Double.parseDouble(maxtxt1.getText());
        double maxValue2;
        maxValue2 = Double.parseDouble(maxtxt2.getText());
        
        //Calculation
        double maxResult = Math.max(maxValue1, maxValue2);
        
        //Output
        maxoutputlbl.setText(String.valueOf(maxResult));
    }//GEN-LAST:event_maxbtnActionPerformed

    private void mintxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mintxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mintxt2ActionPerformed

    private void mintxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mintxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mintxt1ActionPerformed

    private void minbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minbtnActionPerformed
        //Min calc code
        //Inputs
        double minValue1;
        minValue1 = Double.parseDouble(mintxt1.getText());
        double minValue2;
        minValue2 = Double.parseDouble(mintxt2.getText());
        
        //Calculation
        double minResult = Math.min(minValue1, minValue2);
        
        //Output
        minoutputlbl.setText(String.valueOf(minResult));
    }//GEN-LAST:event_minbtnActionPerformed

    private void powbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powbtnActionPerformed
        //pow calc code
        DecimalFormat x = new DecimalFormat("###.##");
        //Inputs
        double powValue1;
        powValue1 = Double.parseDouble(powtxt1.getText());
        double powValue2;
        powValue2 = Double.parseDouble(powtxt2.getText());
        
        //Calculation
        double powResult = Math.pow(powValue1, powValue2);
        
        //Output
        powoutputlbl.setText(String.valueOf(x.format(powResult)));
    }//GEN-LAST:event_powbtnActionPerformed

    private void powtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powtxt2ActionPerformed

    private void powtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powtxt1ActionPerformed

    private void hypotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotbtnActionPerformed
        //hypot calc code
        DecimalFormat x = new DecimalFormat("###.##");
        //Inputs
        double hypotValue1;
        hypotValue1 = Double.parseDouble(hypottxt1.getText());
        double hypotValue2;
        hypotValue2 = Double.parseDouble(hypottxt2.getText());
        
        //Calculation
        double hypotResult = Math.hypot(hypotValue1, hypotValue2);
        
        //Output
        hypotoutputlbl.setText(String.valueOf(x.format(hypotResult)));
    }//GEN-LAST:event_hypotbtnActionPerformed

    private void hypottxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypottxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypottxt2ActionPerformed

    private void hypottxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypottxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hypottxt1ActionPerformed

    private void floortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floortxtActionPerformed

    private void floorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorbtnActionPerformed
        //floor calc code
        //Inputs
        double floorValue1;
        floorValue1 = Double.parseDouble(floortxt.getText());
        
        //Calculation
        double floorResult = Math.floor(floorValue1);
        
        //Output
        flooroutputlbl.setText(String.valueOf(floorResult));
    }//GEN-LAST:event_floorbtnActionPerformed

    private void ceiltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceiltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceiltxtActionPerformed

    private void ceilbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceilbtnActionPerformed
        //ceil calc code
        //Inputs
        double ceilValue1;
        ceilValue1 = Double.parseDouble(ceiltxt.getText());
        
        //Calculation
        double ceilResult = Math.ceil(ceilValue1);
        
        //Output
        ceiloutputlbl.setText(String.valueOf(ceilResult));
    }//GEN-LAST:event_ceilbtnActionPerformed

    private void sqrttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqrttxtActionPerformed

    private void sqrtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtbtnActionPerformed
        //sqrt calc code
        DecimalFormat x = new DecimalFormat("###.##");
        //Inputs
        double sqrtValue1;
        sqrtValue1 = Double.parseDouble(sqrttxt.getText());
        
        //Calculation
        double sqrtResult = Math.sqrt(sqrtValue1);
        
        //Output
        sqrtoutputlbl.setText(String.valueOf(x.format(sqrtResult)));
    }//GEN-LAST:event_sqrtbtnActionPerformed

    private void toRadianstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRadianstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toRadianstxtActionPerformed

    private void toRadiansbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRadiansbtnActionPerformed
        //toRadians calc code
        DecimalFormat x = new DecimalFormat("###.##");
        //Inputs
        double toRadiansValue1;
        toRadiansValue1 = Double.parseDouble(toRadianstxt.getText());
        
        //Calculation
        double toRadiansResult = Math.toRadians(toRadiansValue1);
        
        //Output
        toRadiansoutputlbl.setText(String.valueOf(x.format(toRadiansResult)));
    }//GEN-LAST:event_toRadiansbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicMathMethodsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicMathMethodsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicMathMethodsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicMathMethodsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicMathMethodsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ceilbtn;
    private javax.swing.JLabel ceillbl;
    private javax.swing.JLabel ceiloutputlbl;
    private javax.swing.JTextField ceiltxt;
    private javax.swing.JButton floorbtn;
    private javax.swing.JLabel floorlbl;
    private javax.swing.JLabel flooroutputlbl;
    private javax.swing.JTextField floortxt;
    private javax.swing.JButton hypotbtn;
    private javax.swing.JLabel hypotlbl;
    private javax.swing.JLabel hypotoutputlbl;
    private javax.swing.JTextField hypottxt1;
    private javax.swing.JTextField hypottxt2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton maxbtn;
    private javax.swing.JLabel maxlbl;
    private javax.swing.JLabel maxlbl1;
    private javax.swing.JLabel maxoutputlbl;
    private javax.swing.JTextField maxtxt1;
    private javax.swing.JTextField maxtxt2;
    private javax.swing.JButton minbtn;
    private javax.swing.JLabel minoutputlbl;
    private javax.swing.JTextField mintxt1;
    private javax.swing.JTextField mintxt2;
    private javax.swing.JButton powbtn;
    private javax.swing.JLabel powlbl;
    private javax.swing.JLabel powoutputlbl;
    private javax.swing.JTextField powtxt1;
    private javax.swing.JTextField powtxt2;
    private javax.swing.JButton sqrtbtn;
    private javax.swing.JLabel sqrtlbl;
    private javax.swing.JLabel sqrtoutputlbl;
    private javax.swing.JTextField sqrttxt;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JButton toRadiansbtn;
    private javax.swing.JLabel toRadianslbl;
    private javax.swing.JLabel toRadiansoutputlbl;
    private javax.swing.JTextField toRadianstxt;
    // End of variables declaration//GEN-END:variables
}
